version: '3'
services:

  mongoXMK0:
    image: mongo:4.4
    container_name: mongoXKM0
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - db-tier


  km0-api:
    build: .

    restart: always
    depends_on:
      - mongoXMK0
    networks:
      - db-tier


volumes:
  mongo-data:
    driver: local

networks:
  db-tier:
    driver: bridge


